version: '3.3'
services:
  matomo:
    container_name: matomo
    image: matomo
    environment:
      MATOMO_DATABASE_HOST: bbnavi-datahub-postgresql
    networks:
     - internal
     - public
    logging:
      driver: awslogs
    volumes:
      - matomo_data:/var/www/html
    deploy:
      replicas: 1
      labels:
        traefik.http.routers.matomo.tls.certresolver: acme
        traefik.http.services.matomo.loadbalancer.server.port: '80'
        traefik.http.routers.matomo.rule: Host(`matomo.bbnavi.de`)
        traefik.http.routers.matomo.entrypoints: https
        traefik.docker.network: public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.role == worker

volumes:
  matomo_data:
    external: true

networks:
  datahub_bbnavi-datahub-postgresql:
    external: true
  public:
    external: true
  internal:
    driver: overlay