version: '3.3'
services:
  matomo:
    container_name: matomo
    image: matomo:5.0.3
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
      - MATOMO_DATABASE_ADAPTER=MYSQLI
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DATABASE_PASSWORD}
      - MATOMO_DATABASE_DBNAME=matomo
      - MATOMO_DATABASE_PORT=3306
      - MATOMO_DATABASE_SSL=false
    networks:
      - public
      - matomo
    restart: unless-stopped
    logging:
      driver: awslogs
    volumes:
      - matomo_data:/var/www/html
    deploy:
      replicas: 1
      labels:
        traefik.http.routers.nutzung.tls.certresolver: acme
        traefik.http.services.nutzung.loadbalancer.server.port: '80'
        traefik.http.routers.nutzung.rule: Host(`nutzung.bbnavi.de`)
        traefik.http.routers.nutzung.entrypoints: https
        traefik.docker.network: public
        traefik.enable: 'true'
      placement:
        constraints:
         - node.role == worker

  matomo_db:
    container_name: matomo_db
    image: mysql:8.4
    command: --max-allowed-packet=64MB
    networks: 
      - matomo
    environment:
      - MYSQL_ROOT_PASSWORD=${MATOMO_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=matomo
      - MYSQL_DATABASE=matomo
      - MYSQL_PASSWORD=${MATOMO_DATABASE_PASSWORD}
    volumes: 
      - matomo_mysql:/var/lib/mysql:rw
    restart: unless-stopped
    deploy:
      placement:
        constraints:
         - node.role == worker

volumes:
  matomo_mysql:
    external: true
  matomo_data:
    external: true

networks:
  public:
    external: true
  matomo:
    driver: overlay