name: Docker Image CI

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy: 
     runs-on: [self-hosted, deploy]
     needs: build-and-push-image
     env: 
       MYSQL_ROOT_PASSWORD: ${{ secrets.MATOMO_MYSQL_ROOT_PASSWORD }}
       MATOMO_DATABASE_PASSWORD: ${{ secrets.MATOMO_DATABASE_PASSWORD }}
     steps: 
       - uses: actions/checkout@v2
       - name: Deploy Stack
         run: |
           docker stack deploy --compose-file docker-compose.yml bbnavi-matomo
